env:
  browser: true
  es2021: true
  es6: true
  node: true
extends: airbnb
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: latest
  ecmaFeatures:
    impliedStrict: true
  sourceType: module
rules:
  no-use-before-define: off
  react/react-in-jsx-scope: off
  react/jsx-props-no-spreading: off
  jsx-a11y/media-has-caption: off
  indent:
    - 2
  react/jsx-indent:
    - 2
  react/jsx-indent-props:
    - 2
  linebreak-style:
    - 2
  quotes:
    - 2
  semi:
    - 2
